version: '3'

vars:
  TF_DIR: terraform
  ANSIBLE_DIR: ansible

tasks:
  default:
    desc: List all tasks
    cmds:
      - task --list
    silent: true

  init:
    desc: Initialize Terraform
    dir: '{{.TF_DIR}}'
    cmds:
      - doppler run -- terraform init

  plan:
    desc: Plan Terraform changes
    dir: '{{.TF_DIR}}'
    cmds:
      - |
        doppler run -- bash -c './generate_vars.sh && terraform plan -var-file=".proxmox.tfvars.json"; rm -f .proxmox.tfvars.json'

  apply:
    desc: Apply Terraform changes
    dir: '{{.TF_DIR}}'
    cmds:
      - |
        doppler run -- bash -c './generate_vars.sh && terraform apply -var-file=".proxmox.tfvars.json" -auto-approve; rm -f .proxmox.tfvars.json'

  destroy:
    desc: Destroy Terraform resources
    dir: '{{.TF_DIR}}'
    cmds:
      - |
        doppler run -- bash -c './generate_vars.sh && terraform destroy -var-file=".proxmox.tfvars.json" -auto-approve; rm -f .proxmox.tfvars.json'

  output:
    desc: Show Terraform outputs
    dir: '{{.TF_DIR}}'
    cmds:
      - terraform output

  provision:
    desc: Provision and verify the runner
    dir: '{{.ANSIBLE_DIR}}'
    cmds:
      - chmod +x provision.sh
      - doppler run -- ./provision.sh

  status:
    desc: Check the status of the runner service
    dir: '{{.ANSIBLE_DIR}}'
    cmds:
      - chmod +x status.sh
      - doppler run -- ./status.sh