version: '3'

vars:
  PLAYBOOK: playbooks/main.yml
  INVENTORY: inventory/hosts

tasks:
  default:
    desc: List all tasks
    cmds:
      - task --list
    silent: true

  init:
    desc: Install Ansible dependencies
    cmds:
      - ansible-galaxy collection install community.general ansible.posix community.docker
      - ansible-galaxy role install -p roles/ geerlingguy.docker geerlingguy.pip artis3n.tailscale

  plan:
    desc: Run Ansible playbook in check mode (dry run)
    cmds:
      - doppler run -- ansible-playbook -i {{.INVENTORY}} {{.PLAYBOOK}} --check --diff

  apply:
    desc: Run Ansible playbook to apply changes
    cmds:
      - echo "Applying changes..."
      - doppler run -- ansible-playbook -i {{.INVENTORY}} {{.PLAYBOOK}}

  storage-plan:
    desc: Run Ansible playbook in check mode (dry run) for storage only
    cmds:
      - doppler run -- ansible-playbook -i {{.INVENTORY}} {{.PLAYBOOK}} --check --diff --tags storage

  storage-apply:
    desc: Run Ansible playbook to apply changes for storage only
    cmds:
      - echo "Applying changes..."
      - doppler run -- ansible-playbook -i {{.INVENTORY}} {{.PLAYBOOK}} --tags storage