version: '3'

tasks:
  default:
    desc: List all tasks
    cmds:
      - task --list
    silent: true

  init:
    desc: Initialize Terraform
    dir: terraform
    cmds:
      - doppler run -- terraform init

  plan:
    desc: Plan Terraform changes
    dir: terraform
    cmds:
      - |
        doppler run -- sh -c '
          export TF_VAR_portainer_access_token="$PORTAINER_ACCESS_TOKEN"
          export TF_VAR_cloudflare_api_token="$CLOUDFLARE_API_TOKEN"
          export TF_VAR_cloudflare_tunnel_token="$CLOUDFLARE_TUNNEL_TOKEN"
          export TF_VAR_acme_email="${ACME_EMAIL:-$EMAIL}"
          export TF_VAR_apps_domain="$DOMAIN"
          export TF_VAR_beszel_agent_key="$BESZEL_AGENT_KEY"
          export TF_VAR_beszel_agent_token="$BESZEL_AGENT_TOKEN"
          export TF_VAR_homepage_jellyfin_api="$HOMEPAGE_JELLYFIN_API"
          export TF_VAR_docmost_app_secret="$DOCMOST_APP_SECRET"
          export TF_VAR_docmost_postgres_password="$DOCMOST_POSTGRES_PASSWORD"
          terraform plan
        '

  apply:
    desc: Apply Terraform changes
    dir: terraform
    cmds:
      - |
        doppler run -- sh -c '
          export TF_VAR_portainer_access_token="$PORTAINER_ACCESS_TOKEN"
          export TF_VAR_cloudflare_api_token="$CLOUDFLARE_API_TOKEN"
          export TF_VAR_cloudflare_tunnel_token="$CLOUDFLARE_TUNNEL_TOKEN"
          export TF_VAR_acme_email="${ACME_EMAIL:-$EMAIL}"
          export TF_VAR_apps_domain="$DOMAIN"
          export TF_VAR_beszel_agent_key="$BESZEL_AGENT_KEY"
          export TF_VAR_beszel_agent_token="$BESZEL_AGENT_TOKEN"
          export TF_VAR_homepage_jellyfin_api="$HOMEPAGE_JELLYFIN_API"
          export TF_VAR_docmost_app_secret="$DOCMOST_APP_SECRET"
          export TF_VAR_docmost_postgres_password="$DOCMOST_POSTGRES_PASSWORD"
          terraform apply -auto-approve
        '

  destroy:
    desc: Destroy Terraform resources
    dir: terraform
    cmds:
      - |
        doppler run -- sh -c '
          export TF_VAR_portainer_access_token="$PORTAINER_ACCESS_TOKEN"
          export TF_VAR_cloudflare_api_token="$CLOUDFLARE_API_TOKEN"
          export TF_VAR_cloudflare_tunnel_token="$CLOUDFLARE_TUNNEL_TOKEN"
          export TF_VAR_acme_email="${ACME_EMAIL:-$EMAIL}"
          export TF_VAR_apps_domain="$DOMAIN"
          export TF_VAR_beszel_agent_key="$BESZEL_AGENT_KEY"
          export TF_VAR_beszel_agent_token="$BESZEL_AGENT_TOKEN"
          export TF_VAR_homepage_jellyfin_api="$HOMEPAGE_JELLYFIN_API"
          export TF_VAR_docmost_app_secret="$DOCMOST_APP_SECRET"
          export TF_VAR_docmost_postgres_password="$DOCMOST_POSTGRES_PASSWORD"
          terraform destroy -auto-approve
        '
