version: '3'

vars:
  ANSIBLE_DIR: ansible

tasks:
  default:
    desc: List all tasks
    cmds:
      - task --list
    silent: true

  create_template:
    desc: Create the Debian 13 template on Proxmox
    dir: '{{.ANSIBLE_DIR}}'
    cmds:
      - |
        doppler run -- bash -c '
        set -e
        if [ -z "$PROXMOX_HOST" ]; then echo "PROXMOX_HOST not set"; exit 1; fi
        if [ -z "$ANSIBLE_SSH_PRIVATE_KEY" ]; then echo "ANSIBLE_SSH_PRIVATE_KEY not set"; exit 1; fi
        
        KEY_FILE=$(mktemp)
        echo "$ANSIBLE_SSH_PRIVATE_KEY" > "$KEY_FILE"
        chmod 600 "$KEY_FILE"
        trap "rm -f $KEY_FILE" EXIT

        ansible-playbook -i "$PROXMOX_HOST," playbook.yml --private-key "$KEY_FILE" -u root
        '
