version: '3'

vars:
  ANSIBLE_DIR: ansible

tasks:
  default:
    desc: List all tasks
    cmds:
      - task --list
    silent: true

  create_template:
    desc: Create the Debian 13 template on Proxmox (runs in Docker via script)
    dir: '{{.ANSIBLE_DIR}}'
    cmds:
      - doppler run -- ./create_template.sh